"""empty message

Revision ID: 397451b94ebf
Revises: c00cfa9d419e
Create Date: 2023-07-28 14:12:22.751210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '397451b94ebf'
down_revision = 'c00cfa9d419e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_history',
    sa.Column('history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orderer_id', sa.Integer(), nullable=False),
    sa.Column('menu_pk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_pk'], ['menu.menu_pk'], ),
    sa.ForeignKeyConstraint(['orderer_id'], ['orderer.orderer_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.drop_table('order_summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_summary',
    sa.Column('summary_id', sa.INTEGER(), nullable=False),
    sa.Column('orderer_id', sa.INTEGER(), nullable=False),
    sa.Column('menu_name', sa.VARCHAR(), nullable=False),
    sa.Column('menu_count', sa.INTEGER(), nullable=False),
    sa.Column('menu_price', sa.INTEGER(), nullable=False),
    sa.Column('total_price', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['orderer_id'], ['orderer.orderer_id'], ),
    sa.PrimaryKeyConstraint('summary_id')
    )
    op.drop_table('order_history')
    # ### end Alembic commands ###
