"""empty message

Revision ID: 467690dce96c
Revises: 779dd00bc81a
Create Date: 2023-08-01 22:02:27.977658

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '467690dce96c'
down_revision = '779dd00bc81a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('option',
    sa.Column('option_pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('option_name', sa.String(length=50), nullable=False),
    sa.Column('option_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('option_pk'),
    schema='kiosk'
    )
    op.drop_constraint('menu_ibfk_1', 'menu', type_='foreignkey')
    op.create_foreign_key(None, 'menu', 'categories', ['category_pk'], ['category_pk'], source_schema='kiosk', referent_schema='kiosk')
    op.add_column('order_detail', sa.Column('options_pk', sa.Integer(), nullable=True))
    op.drop_constraint('order_detail_ibfk_2', 'order_detail', type_='foreignkey')
    op.drop_constraint('order_detail_ibfk_1', 'order_detail', type_='foreignkey')
    op.create_foreign_key(None, 'order_detail', 'option', ['options_pk'], ['option_pk'], source_schema='kiosk', referent_schema='kiosk')
    op.create_foreign_key(None, 'order_detail', 'orderer', ['orderer_id'], ['orderer_id'], source_schema='kiosk', referent_schema='kiosk')
    op.create_foreign_key(None, 'order_detail', 'menu', ['menu_pk'], ['menu_pk'], source_schema='kiosk', referent_schema='kiosk')
    op.drop_column('order_detail', 'menu_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_detail', sa.Column('menu_count', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order_detail', schema='kiosk', type_='foreignkey')
    op.drop_constraint(None, 'order_detail', schema='kiosk', type_='foreignkey')
    op.drop_constraint(None, 'order_detail', schema='kiosk', type_='foreignkey')
    op.create_foreign_key('order_detail_ibfk_1', 'order_detail', 'orderer', ['orderer_id'], ['orderer_id'])
    op.create_foreign_key('order_detail_ibfk_2', 'order_detail', 'menu', ['menu_pk'], ['menu_pk'])
    op.drop_column('order_detail', 'options_pk')
    op.drop_constraint(None, 'menu', schema='kiosk', type_='foreignkey')
    op.create_foreign_key('menu_ibfk_1', 'menu', 'categories', ['category_pk'], ['category_pk'])
    op.drop_table('option', schema='kiosk')
    # ### end Alembic commands ###
