"""empty message

Revision ID: 6c730e76f2de
Revises: 3023279b2edc
Create Date: 2023-07-31 15:04:18.805032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c730e76f2de'
down_revision = '3023279b2edc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_option',
    sa.Column('order_option_pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_detail_pk', sa.Integer(), nullable=False),
    sa.Column('option_pk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['option_pk'], ['options.option_pk'], ),
    sa.ForeignKeyConstraint(['order_detail_pk'], ['order_detail.order_detail_pk'], ),
    sa.PrimaryKeyConstraint('order_option_pk')
    )
    op.drop_table('order_options')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_options',
    sa.Column('order_option_pk', sa.INTEGER(), nullable=False),
    sa.Column('order_detail_pk', sa.INTEGER(), nullable=False),
    sa.Column('option_pk', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['option_pk'], ['options.option_pk'], ),
    sa.ForeignKeyConstraint(['order_detail_pk'], ['order_detail.order_detail_pk'], ),
    sa.PrimaryKeyConstraint('order_option_pk')
    )
    op.drop_table('order_option')
    # ### end Alembic commands ###
