"""empty message

Revision ID: 8e53f0e19802
Revises: 0209c0b7e8a7
Create Date: 2023-07-31 14:45:17.970130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e53f0e19802'
down_revision = '0209c0b7e8a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
