"""empty message

Revision ID: 9d643ce50420
Revises: dc040d1dead5
Create Date: 2023-07-28 01:38:01.152611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d643ce50420'
down_revision = 'dc040d1dead5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orderer', 'orderer_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderer', sa.Column('orderer_address', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
