"""empty message

Revision ID: c00cfa9d419e
Revises: 9d643ce50420
Create Date: 2023-07-28 14:00:11.651852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c00cfa9d419e'
down_revision = '9d643ce50420'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_summary',
    sa.Column('summary_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orderer_id', sa.Integer(), nullable=False),
    sa.Column('menu_name', sa.String(), nullable=False),
    sa.Column('menu_count', sa.Integer(), nullable=False),
    sa.Column('menu_price', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['orderer_id'], ['orderer.orderer_id'], ),
    sa.PrimaryKeyConstraint('summary_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_summary')
    # ### end Alembic commands ###
