"""empty message

Revision ID: ce1b65474c6d
Revises: 
Create Date: 2023-08-02 01:02:01.634191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce1b65474c6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('category_pk'),
    schema='kiosk'
    )
    op.create_table('option',
    sa.Column('option_pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('option_name', sa.String(length=50), nullable=False),
    sa.Column('option_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('option_pk'),
    schema='kiosk'
    )
    op.create_table('orderer',
    sa.Column('orderer_id', sa.Integer(), nullable=False),
    sa.Column('orderer_name', sa.String(length=50), nullable=False),
    sa.Column('orderer_phone', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('orderer_id'),
    schema='kiosk'
    )
    op.create_index(op.f('ix_kiosk_orderer_orderer_id'), 'orderer', ['orderer_id'], unique=False, schema='kiosk')
    op.create_table('menu',
    sa.Column('menu_pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('menu_name', sa.String(length=50), nullable=False),
    sa.Column('menu_price', sa.Integer(), nullable=False),
    sa.Column('menu_description', sa.String(length=50), nullable=False),
    sa.Column('category_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_pk'], ['kiosk.categories.category_pk'], ),
    sa.PrimaryKeyConstraint('menu_pk'),
    schema='kiosk'
    )
    op.create_table('order_detail',
    sa.Column('order_detail_pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orderer_id', sa.Integer(), nullable=True),
    sa.Column('menu_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['menu_pk'], ['kiosk.menu.menu_pk'], ),
    sa.ForeignKeyConstraint(['orderer_id'], ['kiosk.orderer.orderer_id'], ),
    sa.PrimaryKeyConstraint('order_detail_pk'),
    schema='kiosk'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_detail', schema='kiosk')
    op.drop_table('menu', schema='kiosk')
    op.drop_index(op.f('ix_kiosk_orderer_orderer_id'), table_name='orderer', schema='kiosk')
    op.drop_table('orderer', schema='kiosk')
    op.drop_table('option', schema='kiosk')
    op.drop_table('categories', schema='kiosk')
    # ### end Alembic commands ###
