"""empty message

Revision ID: d658c1c5bd99
Revises: 
Create Date: 2023-07-27 22:23:51.557220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd658c1c5bd99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('category_pk')
    )
    op.create_table('orderer',
    sa.Column('orderer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orderer_name', sa.String(), nullable=False),
    sa.Column('orderer_phone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('orderer_id')
    )
    op.create_table('menu',
    sa.Column('menu_pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('menu_name', sa.String(), nullable=False),
    sa.Column('menu_price', sa.Integer(), nullable=False),
    sa.Column('menu_description', sa.String(), nullable=False),
    sa.Column('category_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_pk'], ['categories.category_pk'], ),
    sa.PrimaryKeyConstraint('menu_pk')
    )
    op.create_table('order_detail',
    sa.Column('order_detail_pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orderer_id', sa.Integer(), nullable=True),
    sa.Column('menu_pk', sa.Integer(), nullable=True),
    sa.Column('menu_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_pk'], ['menu.menu_pk'], ),
    sa.ForeignKeyConstraint(['orderer_id'], ['orderer.orderer_id'], ),
    sa.PrimaryKeyConstraint('order_detail_pk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_detail')
    op.drop_table('menu')
    op.drop_table('orderer')
    op.drop_table('categories')
    # ### end Alembic commands ###
